#!/usr/bin/env python3
"""Rebuild the horizontal logo lock-up with the wordmark as outlines.

The wordmark is converted to paths rather than left as <text> so the asset
renders identically everywhere without the font installed - which matters for
a logo that ends up in READMEs, release pages and other people's browsers.

Run after changing the text, the size or the tracking:

    pip install fonttools
    python deploy/generate_wordmark.py

The mark itself (the three bars) is duplicated here and in
client/images/AbstractumVPN_logo.svg. If the geometry changes, change both.
"""

import os
import sys

try:
    from fontTools.ttLib import TTFont
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.misc.transform import Transform
except ImportError:
    sys.exit("fontTools is required: pip install fonttools")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, "client", "fonts", "JetBrainsMono-SemiBold.ttf")
OUT_DIR = os.path.join(ROOT, "client", "images")

SIZE = 24.0        # cap size in SVG units
BASELINE = 41.0
START_X = 78.0     # clears the mark, which ends at x=58
TRACKING = -0.4

# Two variants, because GitHub renders READMEs in both themes and no single
# steel works in both: #9BBFDE is 9.8:1 on GitHub dark but 1.9:1 on white.
THEMES = {
    "":       dict(ink="#D7D8DB", steel="#9BBFDE", muted="#3E5D75"),  # dark bg
    "_light": dict(ink="#24292F", steel="#2A6389", muted="#7FA3BE"),  # light bg
}


def run(glyphs, cmap, hmtx, upm, text, x):
    """Draw `text` starting at `x`; return (path data, x after the last glyph)."""
    parts, cur, scale = [], x, SIZE / upm
    for ch in text:
        name = cmap.get(ord(ch))
        if name is None:
            continue
        pen = SVGPathPen(glyphs)
        # Font Y grows upwards, SVG Y grows downwards, hence the negative scale.
        glyphs[name].draw(TransformPen(
            pen, Transform(scale, 0, 0, -scale, cur, BASELINE)))
        data = pen.getCommands()
        if data:
            parts.append(data)
        cur += hmtx[name][0] * scale + TRACKING
    return " ".join(parts), cur


def main():
    font = TTFont(FONT)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    hmtx, upm = font["hmtx"], font["head"].unitsPerEm

    name_path, x = run(glyphs, cmap, hmtx, upm, "Abstractum", START_X)
    vpn_path, end = run(glyphs, cmap, hmtx, upm, "VPN", x)
    width = round(end + 10)

    for suffix, c in THEMES.items():
        INK, STEEL, STEEL_MUTED = c["ink"], c["steel"], c["muted"]
        OUT = os.path.join(OUT_DIR, f"AbstractumVPN_Full_logo{suffix}.svg")
        svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 64" width="{width}" height="64" role="img" aria-label="AbstractumVPN">
  <title>AbstractumVPN</title>
  <!--
    Generated by deploy/generate_wordmark.py - do not edit the paths by hand.

    The mark geometry is duplicated from AbstractumVPN_logo.svg; keep both in
    sync. The wordmark is JetBrains Mono SemiBold converted to outlines, so no
    font needs to be installed to render this correctly. The font is vendored at
    client/fonts/JetBrainsMono-SemiBold.ttf under the SIL Open Font License 1.1
    (client/fonts/JetBrainsMono-OFL.txt).
  -->
  <g>
    <rect x="6"  y="16" width="40" height="8" rx="4" fill="{STEEL}"/>
    <rect x="18" y="28" width="40" height="8" rx="4" fill="{STEEL_MUTED}"/>
    <rect x="6"  y="40" width="40" height="8" rx="4" fill="{STEEL}"/>
  </g>
  <path fill="{INK}" d="{name_path}"/>
  <path fill="{STEEL}" d="{vpn_path}"/>
</svg>
'''
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(svg)
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({width}x64)")


if __name__ == "__main__":
    main()
